### PR TITLE
Hamor player bank

### PR DESCRIPTION
**Pull request by bhamor**
Added Player and Bank.  They have very basic functions and I'm starting to think that I've kinda turned everything into "data classes" which is supposed to be a bad thing.  I dunno.  Let me know what you guys think.

### CODE REVIEW

**Comment by TatroCSU** [comment]
It looks pretty good so far.

**Comment by bhamor** [comment]
I'm not really sure whats up with those xmls because I did not commit those and android studio is not showing that I committed and xmls.

**Comment by ajcopley** [comment]
Need to add canAfford method to player.

**Review by jameson28 — COMMENTED** [review]
Don't worry, I don't think they are data classes.  Each one has tracks and changes data.

**Pull request merged**
